# Generated by Django 3.2.19 on 2023-06-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_by',
            new_name='owner',
        ),
    ]
