# Generated by Django 3.2.19 on 2023-07-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subtitle',
        ),
    ]
